import { NextResponse } from "next/server";
import { prisma } from "@/lib/db";

export async function POST() {
  try {
    await prisma.product.deleteMany();
    await prisma.productCategory.deleteMany();

    await prisma.productCategory.createMany({
      data: [
        {
          id: "cat-001",
          name: "Electronics",
          description: "Electronic devices and accessories",
        },
        {
          id: "cat-002",
          name: "Clothing",
          description: "Apparel and fashion items",
        },
        {
          id: "cat-003",
          name: "Home & Garden",
          description: "Home improvement and garden supplies",
        },
        {
          id: "cat-004",
          name: "Sports",
          description: "Sports equipment and accessories",
        },
        {
          id: "cat-005",
          name: "Books",
          description: "Books and reading materials",
        },
      ],
    });

    const electronicsProducts = [
      {
        name: "Wireless Mouse",
        sku: "ELEC-001",
        description: "Ergonomic wireless mouse",
        price: 29.99,
        stock: 150,
        categoryId: "cat-001",
      },
      {
        name: "Mechanical Keyboard",
        sku: "ELEC-002",
        description: "RGB mechanical keyboard",
        price: 89.99,
        stock: 75,
        categoryId: "cat-001",
      },
      {
        name: "USB-C Hub",
        sku: "ELEC-003",
        description: "7-port USB-C hub",
        price: 49.99,
        stock: 3,
        categoryId: "cat-001",
      },
      {
        name: "Webcam HD",
        sku: "ELEC-004",
        description: "1080p webcam with microphone",
        price: 69.99,
        stock: 45,
        categoryId: "cat-001",
      },
      {
        name: "Monitor Stand",
        sku: "ELEC-005",
        description: "Adjustable monitor stand",
        price: 39.99,
        stock: 8,
        categoryId: "cat-001",
      },
      {
        name: "HDMI Cable",
        sku: "ELEC-006",
        description: "6ft HDMI 2.1 cable",
        price: 14.99,
        stock: 200,
        categoryId: "cat-001",
      },
      {
        name: "Laptop Stand",
        sku: "ELEC-007",
        description: "Aluminum laptop stand",
        price: 34.99,
        stock: 5,
        categoryId: "cat-001",
      },
      {
        name: "Bluetooth Speaker",
        sku: "ELEC-008",
        description: "Portable bluetooth speaker",
        price: 59.99,
        stock: 60,
        categoryId: "cat-001",
      },
      {
        name: "Phone Charger",
        sku: "ELEC-009",
        description: "65W fast charger",
        price: 24.99,
        stock: 4,
        categoryId: "cat-001",
      },
      {
        name: "Ethernet Cable",
        sku: "ELEC-010",
        description: "Cat6 ethernet cable 10ft",
        price: 9.99,
        stock: 300,
        categoryId: "cat-001",
      },
      {
        name: "Power Strip",
        sku: "ELEC-011",
        description: "Surge protector power strip",
        price: 19.99,
        stock: 85,
        categoryId: "cat-001",
      },
      {
        name: "Mouse Pad",
        sku: "ELEC-012",
        description: "Large gaming mouse pad",
        price: 12.99,
        stock: 120,
        categoryId: "cat-001",
      },
      {
        name: "USB Flash Drive",
        sku: "ELEC-013",
        description: "128GB USB 3.0 flash drive",
        price: 15.99,
        stock: 7,
        categoryId: "cat-001",
      },
      {
        name: "Wireless Earbuds",
        sku: "ELEC-014",
        description: "True wireless earbuds",
        price: 79.99,
        stock: 35,
        categoryId: "cat-001",
      },
      {
        name: "Screen Cleaner",
        sku: "ELEC-015",
        description: "Screen cleaning kit",
        price: 8.99,
        stock: 2,
        categoryId: "cat-001",
      },
    ];

    const clothingProducts = [
      {
        name: "Cotton T-Shirt",
        sku: "CLTH-001",
        description: "Classic cotton t-shirt",
        price: 19.99,
        stock: 100,
        categoryId: "cat-002",
      },
      {
        name: "Denim Jeans",
        sku: "CLTH-002",
        description: "Classic fit denim jeans",
        price: 49.99,
        stock: 60,
        categoryId: "cat-002",
      },
      {
        name: "Hoodie",
        sku: "CLTH-003",
        description: "Comfortable pullover hoodie",
        price: 39.99,
        stock: 45,
        categoryId: "cat-002",
      },
      {
        name: "Running Shoes",
        sku: "CLTH-004",
        description: "Lightweight running shoes",
        price: 89.99,
        stock: 6,
        categoryId: "cat-002",
      },
      {
        name: "Winter Jacket",
        sku: "CLTH-005",
        description: "Insulated winter jacket",
        price: 129.99,
        stock: 25,
        categoryId: "cat-002",
      },
      {
        name: "Baseball Cap",
        sku: "CLTH-006",
        description: "Adjustable baseball cap",
        price: 14.99,
        stock: 80,
        categoryId: "cat-002",
      },
      {
        name: "Dress Shirt",
        sku: "CLTH-007",
        description: "Formal dress shirt",
        price: 44.99,
        stock: 9,
        categoryId: "cat-002",
      },
      {
        name: "Socks Pack",
        sku: "CLTH-008",
        description: "6-pair athletic socks",
        price: 12.99,
        stock: 150,
        categoryId: "cat-002",
      },
      {
        name: "Leather Belt",
        sku: "CLTH-009",
        description: "Genuine leather belt",
        price: 29.99,
        stock: 4,
        categoryId: "cat-002",
      },
      {
        name: "Sunglasses",
        sku: "CLTH-010",
        description: "Polarized sunglasses",
        price: 34.99,
        stock: 55,
        categoryId: "cat-002",
      },
      {
        name: "Wool Sweater",
        sku: "CLTH-011",
        description: "Merino wool sweater",
        price: 69.99,
        stock: 3,
        categoryId: "cat-002",
      },
      {
        name: "Cargo Shorts",
        sku: "CLTH-012",
        description: "Multi-pocket cargo shorts",
        price: 29.99,
        stock: 70,
        categoryId: "cat-002",
      },
      {
        name: "Flip Flops",
        sku: "CLTH-013",
        description: "Beach flip flops",
        price: 9.99,
        stock: 200,
        categoryId: "cat-002",
      },
      {
        name: "Watch",
        sku: "CLTH-014",
        description: "Analog wristwatch",
        price: 59.99,
        stock: 7,
        categoryId: "cat-002",
        active: false,
      },
      {
        name: "Scarf",
        sku: "CLTH-015",
        description: "Cashmere scarf",
        price: 49.99,
        stock: 1,
        categoryId: "cat-002",
      },
    ];

    const homeProducts = [
      {
        name: "Table Lamp",
        sku: "HOME-001",
        description: "Modern LED table lamp",
        price: 44.99,
        stock: 40,
        categoryId: "cat-003",
      },
      {
        name: "Plant Pot",
        sku: "HOME-002",
        description: "Ceramic plant pot",
        price: 19.99,
        stock: 90,
        categoryId: "cat-003",
      },
      {
        name: "Throw Pillow",
        sku: "HOME-003",
        description: "Decorative throw pillow",
        price: 24.99,
        stock: 6,
        categoryId: "cat-003",
      },
      {
        name: "Wall Clock",
        sku: "HOME-004",
        description: "Silent wall clock",
        price: 29.99,
        stock: 50,
        categoryId: "cat-003",
      },
      {
        name: "Picture Frame",
        sku: "HOME-005",
        description: "8x10 picture frame",
        price: 14.99,
        stock: 8,
        categoryId: "cat-003",
      },
      {
        name: "Candle Set",
        sku: "HOME-006",
        description: "Scented candle set",
        price: 22.99,
        stock: 75,
        categoryId: "cat-003",
      },
      {
        name: "Doormat",
        sku: "HOME-007",
        description: "Welcome doormat",
        price: 19.99,
        stock: 5,
        categoryId: "cat-003",
      },
      {
        name: "Curtains",
        sku: "HOME-008",
        description: "Blackout curtains pair",
        price: 39.99,
        stock: 30,
        categoryId: "cat-003",
      },
      {
        name: "Bathroom Mat",
        sku: "HOME-009",
        description: "Non-slip bathroom mat",
        price: 17.99,
        stock: 4,
        categoryId: "cat-003",
      },
      {
        name: "Kitchen Towels",
        sku: "HOME-010",
        description: "Cotton kitchen towels set",
        price: 12.99,
        stock: 100,
        categoryId: "cat-003",
      },
      {
        name: "Garden Hose",
        sku: "HOME-011",
        description: "50ft expandable garden hose",
        price: 34.99,
        stock: 9,
        categoryId: "cat-003",
      },
      {
        name: "Bird Feeder",
        sku: "HOME-012",
        description: "Hanging bird feeder",
        price: 24.99,
        stock: 35,
        categoryId: "cat-003",
      },
      {
        name: "Tool Set",
        sku: "HOME-013",
        description: "Basic home tool set",
        price: 59.99,
        stock: 2,
        categoryId: "cat-003",
      },
      {
        name: "Storage Box",
        sku: "HOME-014",
        description: "Plastic storage container",
        price: 11.99,
        stock: 120,
        categoryId: "cat-003",
      },
      {
        name: "Shower Curtain",
        sku: "HOME-015",
        description: "Waterproof shower curtain",
        price: 19.99,
        stock: 7,
        categoryId: "cat-003",
        active: false,
      },
    ];

    const sportsProducts = [
      {
        name: "Yoga Mat",
        sku: "SPRT-001",
        description: "Non-slip yoga mat",
        price: 29.99,
        stock: 60,
        categoryId: "cat-004",
      },
      {
        name: "Dumbbells Set",
        sku: "SPRT-002",
        description: "Adjustable dumbbells pair",
        price: 89.99,
        stock: 8,
        categoryId: "cat-004",
      },
      {
        name: "Resistance Bands",
        sku: "SPRT-003",
        description: "Set of 5 resistance bands",
        price: 19.99,
        stock: 100,
        categoryId: "cat-004",
      },
      {
        name: "Water Bottle",
        sku: "SPRT-004",
        description: "Insulated water bottle",
        price: 24.99,
        stock: 3,
        categoryId: "cat-004",
      },
      {
        name: "Jump Rope",
        sku: "SPRT-005",
        description: "Speed jump rope",
        price: 12.99,
        stock: 80,
        categoryId: "cat-004",
      },
      {
        name: "Basketball",
        sku: "SPRT-006",
        description: "Official size basketball",
        price: 34.99,
        stock: 6,
        categoryId: "cat-004",
      },
      {
        name: "Tennis Racket",
        sku: "SPRT-007",
        description: "Lightweight tennis racket",
        price: 69.99,
        stock: 25,
        categoryId: "cat-004",
      },
      {
        name: "Gym Bag",
        sku: "SPRT-008",
        description: "Large gym duffel bag",
        price: 39.99,
        stock: 45,
        categoryId: "cat-004",
      },
      {
        name: "Foam Roller",
        sku: "SPRT-009",
        description: "High-density foam roller",
        price: 22.99,
        stock: 4,
        categoryId: "cat-004",
      },
      {
        name: "Soccer Ball",
        sku: "SPRT-010",
        description: "Match quality soccer ball",
        price: 29.99,
        stock: 55,
        categoryId: "cat-004",
      },
      {
        name: "Cycling Gloves",
        sku: "SPRT-011",
        description: "Padded cycling gloves",
        price: 19.99,
        stock: 9,
        categoryId: "cat-004",
      },
      {
        name: "Swim Goggles",
        sku: "SPRT-012",
        description: "Anti-fog swim goggles",
        price: 14.99,
        stock: 70,
        categoryId: "cat-004",
      },
      {
        name: "Fitness Tracker",
        sku: "SPRT-013",
        description: "Waterproof fitness tracker",
        price: 49.99,
        stock: 5,
        categoryId: "cat-004",
      },
      {
        name: "Golf Balls",
        sku: "SPRT-014",
        description: "12-pack golf balls",
        price: 24.99,
        stock: 40,
        categoryId: "cat-004",
      },
      {
        name: "Kettlebell",
        sku: "SPRT-015",
        description: "20lb kettlebell",
        price: 44.99,
        stock: 2,
        categoryId: "cat-004",
      },
    ];

    const booksProducts = [
      {
        name: "Programming Guide",
        sku: "BOOK-001",
        description: "Modern programming concepts",
        price: 39.99,
        stock: 50,
        categoryId: "cat-005",
      },
      {
        name: "Fiction Novel",
        sku: "BOOK-002",
        description: "Bestselling fiction novel",
        price: 14.99,
        stock: 6,
        categoryId: "cat-005",
      },
      {
        name: "Cookbook",
        sku: "BOOK-003",
        description: "Healthy recipes cookbook",
        price: 24.99,
        stock: 35,
        categoryId: "cat-005",
      },
      {
        name: "Self-Help Book",
        sku: "BOOK-004",
        description: "Personal development guide",
        price: 19.99,
        stock: 4,
        categoryId: "cat-005",
      },
      {
        name: "History Book",
        sku: "BOOK-005",
        description: "World history overview",
        price: 29.99,
        stock: 45,
        categoryId: "cat-005",
      },
      {
        name: "Science Encyclopedia",
        sku: "BOOK-006",
        description: "Illustrated science encyclopedia",
        price: 44.99,
        stock: 8,
        categoryId: "cat-005",
      },
      {
        name: "Biography",
        sku: "BOOK-007",
        description: "Inspiring biography",
        price: 22.99,
        stock: 60,
        categoryId: "cat-005",
      },
      {
        name: "Children Book",
        sku: "BOOK-008",
        description: "Illustrated children story",
        price: 12.99,
        stock: 3,
        categoryId: "cat-005",
      },
      {
        name: "Travel Guide",
        sku: "BOOK-009",
        description: "World travel guide",
        price: 19.99,
        stock: 70,
        categoryId: "cat-005",
      },
      {
        name: "Art Book",
        sku: "BOOK-010",
        description: "Modern art collection",
        price: 49.99,
        stock: 9,
        categoryId: "cat-005",
      },
      {
        name: "Mystery Novel",
        sku: "BOOK-011",
        description: "Thrilling mystery novel",
        price: 16.99,
        stock: 5,
        categoryId: "cat-005",
      },
      {
        name: "Business Book",
        sku: "BOOK-012",
        description: "Business strategy guide",
        price: 27.99,
        stock: 40,
        categoryId: "cat-005",
      },
      {
        name: "Poetry Collection",
        sku: "BOOK-013",
        description: "Classic poetry anthology",
        price: 18.99,
        stock: 7,
        categoryId: "cat-005",
      },
      {
        name: "Language Guide",
        sku: "BOOK-014",
        description: "Foreign language learning",
        price: 24.99,
        stock: 55,
        categoryId: "cat-005",
      },
      {
        name: "Comic Book",
        sku: "BOOK-015",
        description: "Graphic novel collection",
        price: 21.99,
        stock: 1,
        categoryId: "cat-005",
        active: false,
      },
    ];

    await prisma.product.createMany({
      data: [
        ...electronicsProducts,
        ...clothingProducts,
        ...homeProducts,
        ...sportsProducts,
        ...booksProducts,
      ],
    });

    return NextResponse.json({
      success: true,
      message: "Database seeded with categories and products",
    });
  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json(
      { success: false, error: String(error) },
      { status: 500 },
    );
  }
}
